.TH "Sequence< T >" 3 "Wed Feb 1 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sequence< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBappend\fP (T element)"
.br
.ti -1c
.RI "T \fBat\fP (int index) const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBappend\fP (T element)"
.br
.ti -1c
.RI "T \fBat\fP (int index) const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
