.TH "Statistics" 3 "Wed Feb 1 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddNumber\fP (double num)"
.br
.ti -1c
.RI "double \fBMean\fP () const"
.br
.ti -1c
.RI "double \fBStandardDeviation\fP () const"
.br
.ti -1c
.RI "void \fBAddNumber\fP (double num)"
.br
.ti -1c
.RI "double \fBMean\fP () const"
.br
.ti -1c
.RI "double \fBStandardDeviation\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
